version: 2.1
orbs:
  windows: circleci/windows@2.4.0

workflows:
  build:
    jobs:
      - lint
      - flow
      - test:
          version: 8-stretch
          requires:
            - lint
            - flow
      - test:
          version: 10-stretch
          requires:
            - lint
            - flow
      - test:
          version: lts-stretch
          requires:
            - lint
            - flow
      - test:
          version: current-stretch
          requires:
            - lint
            - flow
      - windowstest:
          version: 8-stretch
          requires:
            - lint
            - flow
      - windowstest:
          version: 10-stretch
          requires:
            - lint
            - flow
      - windowstest:
          version: lts-stretch
          requires:
            - lint
            - flow
      - windowstest:
          version: current-stretch
          requires:
            - lint
            - flow

jobs:
  lint:
    docker:
      - image: circleci/node:current-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run lint
          command: npm run lint
          
  flow:
    docker:
      - image: circleci/node:current-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run flow
          command: npm run flow

  test:
    parameters:
      version:
        type: string

    docker:
      - image: circleci/node:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm run jest

  windowstest:
    executor: win/default
    parameters:
      version:
        type: string

    working_directory: ~/repo

    steps:
      - checkout
      - run: msiexec /i https://nodejs.org/dist/v12.16.1/node-v12.16.1-x64.msi
      - run: npm ci
      - run: npm run jest
    
